export const portfolios = [
    {
        id: 1,
        category: "JavaScript",
        title: "Quack - The birdwatcher App",
        text: "Full Stack App",
        link1: 'https://www.google.com',
        link2: 'https://www.google.com',
        img: "images/birdwatcher.png",

    },
    {
        id: 2,
        category: "JavaScript",
        title: "PWA Budget Tracker",
        text: "Progressive Web Apps",
        link1: 'https://www.google.com',
        link2: 'https://www.google.com',
        img: "images/budget_tracker.png",
    },
    {
        id: 3,
        category: "ReactJS",
        title: "Book Search Engine",
        text: "MERN Stack/Apollo Server/React Js",
        link1: 'https://www.google.com',
        link2: 'https://www.google.com',
        img: "images/book_search_engine.png",
    },
    {
        id: 4,
        category: "JavaScript",
        title: "Project-Sports Reel App",
        text: "JavaScript/JQuery",
        link1: 'https://www.google.com',
        link2: 'https://www.google.com',
        img: "images/SportsReel.png",
    },
    {
        id: 5,
        category: "JavaScript",
        title: "Weather-Dashboard App",
        text: "JavaScript/Bootstrap/Serverside APIs",
        link1: 'https://www.google.com',
        link2: 'https://www.google.com',
        img: "images/Weatherdashboard.png",
    },
    {
        id: 6,
        category: "HTML/CSS",
        title: "The Code Refactor Webpage",
        text: "HTML/CSS Technologies",
        link1: 'https://www.google.com',
        link2: 'https://www.google.com',
        img: "images/code-refactor-small.png",
    },
    {
        id: 7,
        category: "ExpressJS",
        title: "The Note-Taker App",
        text: "Express JS Technologies",
        link1: 'https://www.google.com',
        link2: 'https://www.google.com',
        img: "images/notetaker-landingpage.png",
    },
    {
        id: 8,
        category: "NodeJS",
        title: "Team Profile Generator App",
        text: "Node JS Technologies",
        link1: 'https://www.google.com',
        link2: 'https://www.google.com',
        img: "images/Team-profile-webpage.png",
    },
];
