export const portfolios = [
    {
        id: 1,
        category: "JavaScript",
        title: "Quack - The birdwatcher App",
        text: "Full Stack App with HandleBar.js",
        link1: 'https://github.com/BirdWatcherQuack/BirdWatcher',
        link2: 'https://birdwatcherquack.herokuapp.com/',
        img: "images/birdwatcher.png",

    },
    {
        id: 2,
        category: "JavaScript",
        title: "PWA Budget Tracker",
        text: "Progressive Web App",
        link1: 'https://github.com/e-giftz/pwa-budget-tracker',
        link2: 'https://fast-sierra-71282.herokuapp.com/',
        img: "images/budget_tracker.png",
    },
    {
        id: 3,
        category: "ReactJS",
        title: "Book Search Engine",
        text: "MERN Stack/Apollo Server/ReactJS/ExpressJS",
        link1: 'https://github.com/e-giftz/book-search-engine-mern',
        link2: 'https://secret-hollows-41741.herokuapp.com/',
        img: "images/book_search_engine.png",
    },
    {
        id: 4,
        category: "ReactJS",
        title: "Movie Mania",
        text: "Full Stack App with ReactJS, GraphQL, Node.js, ExpressJS and MongoDB",
        link1: 'https://github.com/e-giftz/Movie-Mania',
        link2: 'https://afternoon-fjord-07743.herokuapp.com/',
        img: "images/movie-mania.png",
    },
    {
        id: 5,
        category: "JavaScript",
        title: "Sports Reel App",
        text: "JavaScript/JQuery",
        link1: 'https://github.com/e-giftz/Sports-Reel',
        link2: 'https://e-giftz.github.io/Sports-Reel/',
        img: "images/SportsReel.png",
    },
    {
        id: 6,
        category: "JavaScript",
        title: "Weather-Dashboard App",
        text: "JavaScript/Bootstrap/Serverside APIs",
        link1: 'https://github.com/e-giftz/weather-dashboard',
        link2: 'https://e-giftz.github.io/weather-dashboard/',
        img: "images/Weatherdashboard.png",
    },
    {
        id: 7,
        category: "HTML/CSS",
        title: "The Code Refactor Webpage",
        text: "HTML/CSS Technologies",
        link1: 'https://github.com/e-giftz/Code-Refactor',
        link2: 'https://e-giftz.github.io/Code-Refactor/',
        img: "images/code-refactor-small.png",
    },
    {
        id: 8,
        category: "ExpressJS",
        title: "The Note-Taker App",
        text: "Express JS Technologies",
        link1: 'https://github.com/e-giftz/Note-Taker',
        link2: 'https://www.google.com',
        img: "images/notetaker-landingpage.png",
    },
    {
        id: 9,
        category: "NodeJS",
        title: "Team Profile Generator App",
        text: "Node JS Technologies",
        link1: 'https://github.com/e-giftz/Team-Profile-Generator',
        link2: 'https://github.com/e-giftz/Team-Profile-Generator',
        img: "images/Team-profile-webpage.png",
    },
    {
        id: 10,
        category: "HTML/CSS",
        title: "Work Day Scheduler",
        text: "Dynamically powered HTML/CSS updated with JavaScript/JQuery",
        link1: 'https://github.com/e-giftz/work-day-scheduler',
        link2: 'https://e-giftz.github.io/work-day-scheduler/',
        img: "images/WorkScheduler.png",
    },
    {
        id: 11,
        category: "JavaScript",
        title: "Code Quiz App",
        text: "A timed coding quiz application powered by JavaScript & Web APIs",
        link1: 'https://github.com/e-giftz/code-quiz-app',
        link2: 'https://e-giftz.github.io/code-quiz-app/',
        img: "images/CodeQuizApp.png",
    },
    {
        id: 12,
        category: "JavaScript",
        title: "Password Generator App",
        text: "Random password generating application run on JavaScript",
        link1: 'https://github.com/e-giftz/Password-Generator-Application',
        link2: 'https://e-giftz.github.io/Password-Generator-Application/',
        img: "images/PasswordAppOutput.png",
    },
];
